name: CI/CD Process
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  generate-repo:
    strategy:
      fail-fast: false
      matrix:
        os:
          # Windows is commented out because the same workflow that completes in 2 minutes on Linux takes
          # over 6 hours on Windows.
#          - windows-2025
          - macos-14
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Generate Repository
        run: ./generate-exercise.main.kts
      - name: Regression test 5000 / 1730376609342
        run: ./generate-exercise.main.kts 5000 1730376609342
      - name: Regression test 5000 / 1730376597730
        run: ./generate-exercise.main.kts 5000 1730376597730
      - name: Regression test 5000 / 1730385198056
        run: ./generate-exercise.main.kts 5000 1730385198056
  success:
    runs-on: ubuntu-24.04
    needs:
      - generate-repo
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}